### 登录成功后，向此再发请求；返回教师信息，以及全部课程
GET http://localhost:8080/api/teacher/index
Authorization: {{token}}

###
POST http://localhost:8080/api/teacher/students
Content-Type: application/json
Authorization: {{token}}

{
  "user": {
    "name": "SUN",
    "number": 2017001
  }
}

###
PATCH http://localhost:8080/api/teacher/settings
Content-Type: application/json
Authorization: {{token}}

{
  "quantity": 10,
  "ranges": 30

}

### 查询指定课程
GET http://localhost:8080/api/teacher/courses/1
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8080/api/teacher/welcome
Authorization: {{token}}

### 添加课程
POST http://localhost:8080/api/teacher/courses
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Web"
}
### 全局变量，如果http测试文件被改动，可能失效。须重修登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number" : "1001",
  "password": "1001"

}

> {% client.global.set("token", response.headers.valueOf("Authorization")); %}
###